name: Build Pokeemerald Expansion

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: 'tags/expansion/1.17.0'

      - name: Install ARM compiler and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libpng-dev make

      - name: Build and install agbcc
        run: |
          ./tools/agbcc/build.sh
          ./tools/agbcc/install.sh .

      - name: Compile GBA ROM
        run: make -j$(nproc) DUMP_SYMS=0

      - name: Upload compiled ROM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pokeemerald-1.17.0
          path: pokeemerald.gba
          
