name: Build Pokeemerald Expansion

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Expansion 1.17.0
        uses: actions/checkout@v4
        with:
          repository: 'rh-hideout/pokeemerald-expansion'
          ref: 'expansion/1.17.0'

      - name: Install system dependencies & ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ gcc-arm-none-eabi libpng-dev make git pkg-config

      - name: Build agbcc compiler with legacy C flags
        run: |
          CFLAGS="-w -fcommon -std=gnu89 -Wno-error" ./tools/agbcc/build.sh
          ./tools/agbcc/install.sh .

      - name: Build host binaries and tools
        run: |
          make -C tools/gbagfx
          make -C tools/scaninc
          make -C tools/ramscrgen
          make -C tools/rsfont
          make -C tools/aif2pcm

      - name: Compile GBA ROM
        run: make -j$(nproc) DUMP_SYMS=0

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pokeemerald-1.17.0
          path: pokeemerald.gba
